theme: minima
title: Blog-PowerShell | Where{$_.Content -ge 'Helpful'}
author: Cameron Ove
email: cameronove@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Helpful tips and tricks and indepth write-ups all involving PowerShell.

# social links
twitter_username: cameronove # DO NOT include the @ character, or else the build will fail!
github_username:  cameronove # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
